/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellEntitiesRouteImport } from './routes/_shell.entities'
import { Route as ShellFlagsRouteImport } from './routes/_shell.flags'
import { Route as ShellMediaRouteImport } from './routes/_shell.media'
import { Route as ShellReportRouteImport } from './routes/_shell.report'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellTimelineRouteImport } from './routes/_shell.timeline'
import { Route as ShellUploadRouteImport } from './routes/_shell.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEntitiesRoute = ShellEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFlagsRoute = ShellFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMediaRoute = ShellMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportRoute = ShellReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTimelineRoute = ShellTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUploadRoute = ShellUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ShellDashboardRoute
  '/entities': typeof ShellEntitiesRoute
  '/flags': typeof ShellFlagsRoute
  '/media': typeof ShellMediaRoute
  '/report': typeof ShellReportRoute
  '/settings': typeof ShellSettingsRoute
  '/timeline': typeof ShellTimelineRoute
  '/upload': typeof ShellUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ShellDashboardRoute
  '/entities': typeof ShellEntitiesRoute
  '/flags': typeof ShellFlagsRoute
  '/media': typeof ShellMediaRoute
  '/report': typeof ShellReportRoute
  '/settings': typeof ShellSettingsRoute
  '/timeline': typeof ShellTimelineRoute
  '/upload': typeof ShellUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/entities': typeof ShellEntitiesRoute
  '/_shell/flags': typeof ShellFlagsRoute
  '/_shell/media': typeof ShellMediaRoute
  '/_shell/report': typeof ShellReportRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/timeline': typeof ShellTimelineRoute
  '/_shell/upload': typeof ShellUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/entities'
    | '/flags'
    | '/media'
    | '/report'
    | '/settings'
    | '/timeline'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/entities'
    | '/flags'
    | '/media'
    | '/report'
    | '/settings'
    | '/timeline'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/dashboard'
    | '/_shell/entities'
    | '/_shell/flags'
    | '/_shell/media'
    | '/_shell/report'
    | '/_shell/settings'
    | '/_shell/timeline'
    | '/_shell/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/entities': {
      id: '/_shell/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof ShellEntitiesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/flags': {
      id: '/_shell/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof ShellFlagsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/media': {
      id: '/_shell/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof ShellMediaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/report': {
      id: '/_shell/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ShellReportRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/timeline': {
      id: '/_shell/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof ShellTimelineRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/upload': {
      id: '/_shell/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof ShellUploadRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellEntitiesRoute: typeof ShellEntitiesRoute
  ShellFlagsRoute: typeof ShellFlagsRoute
  ShellMediaRoute: typeof ShellMediaRoute
  ShellReportRoute: typeof ShellReportRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTimelineRoute: typeof ShellTimelineRoute
  ShellUploadRoute: typeof ShellUploadRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellEntitiesRoute: ShellEntitiesRoute,
  ShellFlagsRoute: ShellFlagsRoute,
  ShellMediaRoute: ShellMediaRoute,
  ShellReportRoute: ShellReportRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTimelineRoute: ShellTimelineRoute,
  ShellUploadRoute: ShellUploadRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
